# Site settings
title: Devlxin
email: 1050421454@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Enjoy
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "http://www.devlxin.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  devlxin
GoogleAnalytics: 

twitter:
  username: 
facebook:
  app_id: 
  publisher: 

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
